spring.application.name=reciscore

# Base de datos PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/reciscoredb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

#email
spring.mail.host=smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAIL_USER:}
spring.mail.password=${MAIL_PASS:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.context-path=${CONTEXT_PATH:/}
#CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# IA microservicio
ia.service.url=${IA_SERVICE_URL:http://localhost:8000/classify}

# Tamaño máximo de upload
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB